tasks:
  get_episodes:
    #input - search my trakt list for the next episode that requires collecting
    discover:
      what:
        - next_trakt_episodes:
            username: 
            account: 
            context: collected
            list: Flexget-Shows
            strip_dates: yes
      from:
        - rarbg:
            category: [18, 41]
            sorted_by: seeders
    #filter
    torrent_alive: yes
    content_size:
      max: 3072
      min: 60
    content_filter:
      reject:
        - '*.rar'
        - '*.zip'
    configure_series:
      settings:
        quality: 720p hdtv
      from:
        trakt_list:
          username:
          account: 
          list: Flexget-Shows
          type: shows
          strip_dates: yes
    trakt_lookup:
      username: dave_parki_uk
    if:
      - trakt_watched: reject
      - trakt_collected: reject
    #output
#    download: ~/torrents/
    transmission:
      host: 192.168.1.3
      port: 9091
