tasks:
  get_episodes_trakt:
    #input
    inputs:
      - rss: https://eztv.ag/ezrss.xml
      - rss: http://extratorrent.cc/rss.xml?cid=8
      - rss: http://showrss.info/user/127016.rss?magnets=false&namespaces=true&name=null&quality=null&re=null
    #filter
    torrent_alive: yes
    content_size:
      max: 3072
      min: 60
    content_filter:
      reject:
        - '*.rar'
        - '*.zip'
    configure_series:
      settings:
        quality: hdtv <720p
      from:
        trakt_list:
          username: 
          account: 
          list: Flexget-Shows
          type: shows
          strip_dates: yes
    trakt_lookup:
      username: 
    if:
#      - trakt_watched: reject
      - trakt_collected: reject
    #output
    download: /mnt/nsa_downloads/transmission/torrents/
  
  get_episodes_trakt_hd:
    #input
    inputs:
      - rss: https://eztv.ag/ezrss.xml
      - rss: http://extratorrent.cc/rss.xml?cid=8
      - rss: http://showrss.info/user/127016.rss?magnets=false&namespaces=true&name=null&quality=null&re=null
    #filter
    torrent_alive: yes
    content_size:
      max: 3072
      min: 60
    content_filter:
      reject:
        - '*.rar'
        - '*.zip'
    configure_series:
      settings:
        quality: 720p
      from:
        trakt_list:
          username: 
          account: 
          list: Flexget-Shows-HD
          type: shows
          strip_dates: yes
    trakt_lookup:
      username: 
    if:
#      - trakt_watched: reject
      - trakt_collected: reject
    #output
    download: /mnt/nsa_downloads/transmission/torrents/
          
  get_episodes_showrss_hd:
    #input
    rss: 
    #filter
    torrent_alive: yes
    content_filter:
      reject:
        - '*.rar'
        - '*.zip'
    configure_series:
     # settings:
        #quality: 720p
      from:
        trakt_list:
          username: 
          account: 
          list: Flexget-Shows-HD
          type: shows
          strip_dates: yes
    trakt_lookup:
      username: 
    if:
#      - trakt_watched: reject
      - trakt_collected: reject
    #output
    download: /mnt/nsa_downloads/transmission/torrents/
